alias update='sudo apt update && sudo apt upgrade -y'
alias clean='sudo apt autoremove && sudo apt autoclean'
alias ..='cd ..;pwd'
alias rm='rm -iv'
alias mv='mv -iv'
alias mkdir='mkdir -v'
alias rmdir='rmdir -v'
alias cp='cp -rv'
alias du='du -sh'
alias tree='tree -C'

