theme = "acme"

[editor]
line-number = "relative"
mouse = false
auto-format = true
cursor-shape = {insert = "bar"}
gutters = ["spacer", "line-numbers", "spacer", "diff"]
rulers = [80]
color-modes = true
popup-border = "all"
indent-heuristic = "tree-sitter"
true-color = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.statusline]
left = [
  "spacer", "mode", "file-name", "read-only-indicator", "file-modification-indicator"
]
right = [
  "position", "total-line-numbers", "file-type", "version-control", "spacer"
]
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.inline-diagnostics]
cursor-line = "warning"
prefix-len = 4
