[colors.primary]
background = "#14161b"
foreground = "#e0e2ea"

[colors.normal]
black = "#07080d"
red = "#ffc0b9"
green = "#b3f6c0"
yellow = "#fce094"
blue = "#a6dbff"
magenta = "#ffcaff"
cyan = "#8cf8f7"
white = "#eef1f8"

[colors.bright]
black = "#4f5258"
red = "#ffc0b9"
green = "#b3f6c0"
yellow = "#fce094"
blue = "#a6dbff"
magenta = "#ffcaff"
cyan = "#8cf8f7"
white = "#eef1f8"

[colors.cursor]
text = "#e0e2ea"
cursor = "#9b9ea4"

[colors.selection]
text = "#e0e2ea"
background = "#4f5258"
