hook global WinSetOption filetype=.* %{
    set-option buffer expandtab
    set-option buffer tabstop 2
    set-option buffer indentwidth 2
}

add-highlighter global/ show-matching
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ wrap -word -indent

