set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set-option -g focus-events on
set -g renumber-windows on
set -g set-titles on
set -g mode-keys vi
set -g cursor-style bar

bind-key r source-file ~/.dotfiles/tmux/tmux.conf \; display-message "reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g mouse on
set -g history-limit 32768
set -g bell-action none
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g status-position top
set -g status-justify absolute-centre
set -g window-status-separator "|"
set -g status-left "#S"
set -g status-right ""
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W+ "

set -g pane-active-border-style "fg=#a6dbff"
set -g status-style "bg=default, fg=#4f5258"
set -g message-style "bg=default, fg=#fce094"

set -g window-status-current-style "bg=default, fg=#a6dbff"
